### PR TITLE
fix: enable browser native menu in codemirror plugin

### LINKED ISSUE #180: Source View right click not working
Right click context menu does not work in Source View.

This behavior worked in "4.14.1-liferay.8" when sourcearea was used and stopped working on "4.14.1-liferay.9" when codemirror was used. 

Reproduce:
1. Using CKEditor click Source View.
2. Try right clicking on the editor.

Result: No context menu pops up
Expected: The context menu should appear.

Let me know if there are any questions or comments about this.

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
When we switched to  the `codemirror` plugin, right clicking in source mode no longer worked. 
By adding the `cke_enable_context_menu` CSS class to the `codemirror` plugin, 
the browser's native context menu is enabled.

See [LPS-134687](https://issues.liferay.com/browse/LPS-134687)
Fixes #180

Let me know if there are any questions or comments about this.
Thank you.

### CODE REVIEW

File: plugins/codemirror/plugin.js [hunk 1]
```diff
@@ -36,6 +36,12 @@
 				instance.codeMirrorEditor.setValue(oldData);
 
 				var editableParent = editable.getParent();
+
+				var codeMirrorElement = editableParent.$.getElementsByClassName(
+					'CodeMirror'
+				);
```
Comment (julien) [inline plugins/codemirror/plugin.js:42]: @fortunatomaldonado you can also get a reference to this element with

```js
instance.codeMirrorEditor.getWrapperElement();
```

Which returns the `<div>` element directly and avoids having to deal with an `HTMLCollection`
If you'd rather like a `CKEDITOR.dom.element` object, you can also use 

```js
editableParent.findOne('.CodeMirror');
```

**Comment by julien** [comment]
@fortunatomaldonado I fetched this branch, made a debug build and tried in dxp but unfortunately I still don't see CKEDITOR's context menu in "source mode" - do you have any screenshots of this working? Thanks

**Review by julien — CHANGES_REQUESTED** [review]
Let's use CodeMirror or CKEDITOR's methods to get a reference to elements

**Comment by fortunatomaldonado** [comment]
Hello @julien,

Thank you for taking a look at this! I will make the updates.

I attached a video with the context menu appearing. Let me know what you think.

https://user-images.githubusercontent.com/31672551/123456583-dbd6d680-d597-11eb-8be8-6ee513a2f908.mp4

**Comment by julien** [comment]
@fortunatomaldonado When reading the ticket, I thought we wanted to show CKEditor's custom context menu, and not the browser's native context menu. After doing a build, I can see this working as we expect it to, and the code change seems reasonable to me, so I approve this pull request. Thanks!

**Comment by fortunatomaldonado** [comment]
Hello @julien,

I apologize for not being clear in the ticket of the issue and I will try to be more clear moving forward.
Thank you for the help with this!

**Comment by julien** [comment]
Hey @fortunatomaldonado,
No problem at all - it's totally normal for these things to happen, you did great.
